[connections.snowflake]

account = "PJKGQGQ-CC13792"
user = "VEENEIL"
password = "Khoa01677029171!"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true